spring:
  datasource:
    url: jdbc:mysql://cl-db.c1cyoi64keig.ap-northeast-2.rds.amazonaws.com:3306/cl-db
    username: admin
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:post.sql
jwt:
  issuer: test@gmail.com
  secret-key:  cHJvamVjdENhZmVMb2ctc2VydmljZS1wcm9qZWN0LWp3dFRva2VuLXNlY3JldEtleQo=

