spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update

jwt:
  issuer: test@gmail.com
  secret-key:  cHJvamVjdENhZmVMb2ctc2VydmljZS1wcm9qZWN0LWp3dFRva2VuLXNlY3JldEtleQo=

logging:
  level:
    org.springframework.security: DEBUG
    com.project.cafelogproject: DEBUG


server:
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부