name: CI / CD pipeling

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: gradlew 파일 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: JAR 파일을 서버로 전송
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: build/libs/CafeLog-project-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Exiting the previous jar process
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /home/ubuntu/build/libs/
            JAR_NAME="CafeLog-project-0.0.1-SNAPSHOT.jar"
            PID=$(ps aux | grep "$JAR_NAME" | grep -v grep | awk '{print $2}')

            if [ -n "$PID" ]; then
              echo "이전 프로세스($PID)가 실행 중입니다. 종료를 시도합니다."
              kill $PID
              sleep 10
              if ps -p $PID > /dev/null; then
                echo "프로세스($PID)가 아직 종료되지 않았습니다. 강제 종료를 시도합니다."
                kill -9 $PID
                sleep 5
              fi
              echo "프로세스 종료 완료"
            else
              echo "실행 중인 $JAR_NAME 프로세스가 없습니다."
            fi

      - name: 새로운 JAR 파일 실행
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/build/libs/ 
            echo "현재 작업 디렉토리 확인: $(pwd)"
            JAR_PATH=CafeLog-project-0.0.1-SNAPSHOT.jar
            LOG_FILE=/home/ubuntu/app.log  
            
            if [ -f "$JAR_PATH" ]; then
              echo "JAR 파일을 찾았습니다. 애플리케이션을 시작합니다."

              # nohup을 통해 백그라운드에서 실행하고 로그를 절대 경로에 저장
              nohup java -jar "$JAR_PATH" > "$LOG_FILE" 2>&1 &

              echo "애플리케이션이 백그라운드에서 실행 중입니다."
            else
              echo "JAR 파일을 찾을 수 없습니다!"
              exit 1
            fi